### ISSUE TITLE
canal基本安装配置使用

### ISSUE THREAD

**Issue by Yourwon** [Yourwon/galibang#16]
1、介绍
[](https://github.com/alibaba/canal)
canal [kə'næl]，译意为水道/管道/沟渠，主要用途是基于 MySQL 数据库增量日志解析，提供增量数据订阅和消费。
![image](https://user-images.githubusercontent.com/44433664/187395812-99654e4c-655e-4f87-8a08-ff52913586cd.png)

canal 工作原理
canal 模拟 MySQL slave 的交互协议，伪装自己为 MySQL slave ，向 MySQL master 发送dump 协议
MySQL master 收到 dump 请求，开始推送 binary log 给 slave (即 canal )
canal 解析 binary log 对象(原始为 byte 流)

应用场景：
数据库镜像
数据库实时备份
索引构建和实时维护(拆分异构索引、倒排索引等)
业务 cache 刷新
带业务逻辑的增量数据处理

2、修改mysql的配置，以win10为例

```
#在mysql中创建用户并授权

CREATE USER canal IDENTIFIED BY 'canal';  
GRANT SELECT, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'canal'@'%' identified by 'canal';
#如果本机使用，要加localhost的授权 
GRANT SELECT, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'canal'@'localhost' identified by 'canal';
FLUSH PRIVILEGES;
```

windows默认安装的配置文件
命令行 regedit打开注册表， HKEY_LOCAL_MACHINE-->SYSTEM-->CurrentControlSet-->Services-->MySQL56
![image](https://user-images.githubusercontent.com/44433664/187396767-a97a3e2c-ebc0-4c57-bfa7-fc6a61a02101.png)

修改配置文件，加入
```
[mysqld]
#开启binlog
log-bin=mysql-bin
#行模式
binlog-format=ROW
```

重启后，执行 show VARIABLES like 'log_bin';
![image](https://user-images.githubusercontent.com/44433664/187397176-05d5f4ba-2015-42eb-a706-e60c1dc1b62c.png)

执行 show BINARY logs;
![image](https://user-images.githubusercontent.com/44433664/187397498-a0cd848a-8c51-4043-933f-2f65240f9119.png)

3、下载并解压 canal.deployer-1.1.6.tar
 打开 canal.deployer-1.1.6\conf\example\instance.properties

```
# position info
# 自己的IP端口
canal.instance.master.address=127.0.0.1:3306
#官方文档没有设置 https://github.com/alibaba/canal/wiki/QuickStart
canal.instance.master.journal.name=
canal.instance.master.position=154
canal.instance.master.timestamp=
canal.instance.master.gtid=

# rds oss binlog
canal.instance.rds.accesskey=
canal.instance.rds.secretkey=
canal.instance.rds.instanceId=

# table meta tsdb info
canal.instance.tsdb.enable=true
#canal.instance.tsdb.url=jdbc:mysql://127.0.0.1:3306/canal_tsdb
#canal.instance.tsdb.dbUsername=canal
#canal.instance.tsdb.dbPassword=canal

#canal.instance.standby.address =
#canal.instance.standby.journal.name =
#canal.instance.standby.position =
#canal.instance.standby.timestamp =
#canal.instance.standby.gtid=

# username/password
#自己的用户名密码
canal.instance.dbUsername=canal
canal.instance.dbPassword=canal
canal.instance.connectionCharset = UTF-8
# enable druid Decrypt database password
canal.instance.enableDruid=false
```

4、启动canal.deployer-1.1.6\bin\startup.bat
![image](https://user-images.githubusercontent.com/44433664/187399447-851e3e63-ab71-4300-aab2-0019440e9fa6.png)

5、参照例子构建工程
[](https://github.com/alibaba/canal/wiki/ClientExample)
在数据库中执行操作，控制台会有输出
![image](https://user-images.githubusercontent.com/44433664/187400515-75d8939f-4410-4579-96c8-d0801076c28a.png)

6、
配置MQ模式，配合RocketMQ或者Kafka，canal会把数据发送到MQ的topic中，然后通过消息队列的消费者进行处理。
canal 特别设计了 client-server 模式，交互协议使用 protobuf 3.0
canal 作为 MySQL binlog 增量获取和解析工具，可将变更记录投递到 MQ 系统中，比如 Kafka/RocketMQ，可以借助于 MQ 的多语言能力。

a、修改canal.properties中的配置

```
##################################################
######### 		    RabbitMQ	     #############
##################################################
rabbitmq.host =127.0.0.1
rabbitmq.virtual.host =/
rabbitmq.exchange =canal-test
rabbitmq.username =admin
rabbitmq.password =admin
rabbitmq.deliveryMode =topic
```
b、记录或调整  example instance中的mq topic
```
# tcp, kafka, rocketMQ, rabbitMQ, pulsarMQ
canal.serverMode = rabbitMQ


# mq config
canal.mq.topic=example
```
c、配置rabbitmq
    rabbitmq-plugins list 列出插件
    rabbitmq-plugins enable rabbitmq_management开启web界面管理插件
新建 Exchange: canal-test 类型topic
![image](https://user-images.githubusercontent.com/44433664/189831172-8f5f100b-0cbb-4d0f-b1c3-797bfc2b4b46.png)

新建 Queue example
![image](https://user-images.githubusercontent.com/44433664/189832088-9981ba28-c592-4ed4-88d8-0b9caf30e5b0.png)

绑定
![image](https://user-images.githubusercontent.com/44433664/189832274-6ad2c518-f32e-4a86-85c2-8cd4e5f3d22b.png)

操作数据库，收到消息即表示成功。

![image](https://user-images.githubusercontent.com/44433664/189832563-00e5ea43-5b96-4e7b-a6ca-8d30457654be.png)

d、其他: mysql间的同步
1、NullPointerException 通常是配置文件中缺少相关属性，查看源码增加属性

```
2022-09-14 15:11:06.962 [main] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterService - ## something goes wrong when starting up the canal client adapters:
java.lang.NullPointerException: null
	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.<init>(AdapterProcessor.java:70) ~[client-adapter.launcher-1.1.6.jar:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.CanalAdapterLoader.lambda$init$0(CanalAdapterLoader.java:77) ~[client-adapter.launcher-1.1.6.jar:na]
	at java.util.HashMap.computeIfAbsent(Unknown Source) ~[na:1.8.0_202]
	at com.alibaba.otter.canal.adapter.launcher.loader.CanalAdapterLoader.init(CanalAdapterLoader.java:73) ~[client-adapter.launcher-1.1.6.jar:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.CanalAdapterService.init(CanalAdapterService.java:60) ~[client-adapter.launcher-1.1.6.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_202]
```
	

2、源代码中是 readHeader.clear();  可能是下载的war包是用高版本的JDK进行的打包，在本机的JDK1.8中运行出现问题 
	
```
2022-09-14 15:30:53.180 [Thread-4] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - process error!
java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.readNextPacket(SimpleCanalConnector.java:412) ~[na:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.readNextPacket(SimpleCanalConnector.java:397) ~[na:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:155) ~[na:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.connect(SimpleCanalConnector.java:116) ~[na:na]
	at com.alibaba.otter.canal.connector.tcp.consumer.CanalTCPConsumer.connect(CanalTCPConsumer.java:63) ~[na:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.process(AdapterProcessor.java:185) ~[client-adapter.launcher-1.1.6.jar:na]	
```

3、下载源码，本地运行client-adapter 
![image](https://user-images.githubusercontent.com/44433664/190353544-8af5f210-100a-4b46-9de0-11d7edbb83ff.png)
mysql驱动空指针异常connectTimeout null，尝试在配置中增加相关属性，更换驱动版本到8.0.22后解决。

```
canal.conf:
  mode: tcp #tcp kafka rocketMQ rabbitMQ
  flatMessage: true
  zookeeperHosts:
  syncBatchSize: 1000
  retries: -1
  timeout:
  accessKey:
  secretKey:
  consumerProperties:
    # canal tcp consumer
    canal.tcp.server.host: 127.0.0.1:11111
    canal.tcp.zookeeper.hosts:
    canal.tcp.batch.size: 500
    canal.tcp.username:
    canal.tcp.password:

#  srcDataSources:
    defaultDS:
      url: jdbc:mysql://127.0.0.1:3306/jianw?serverTimezone=Asia/Shanghai&useUnicode=true
      username: root
      password: root

  canalAdapters:
  - instance: example # canal instance Name or mq topic name
    groups:
    - groupId: g1
      outerAdapters:
      - name: logger
      - name: rdb
        key: mysql1
        properties:
          jdbc.driverClassName: com.mysql.cj.jdbc.Driver
          jdbc.url: jdbc:mysql://192.168.95.44:3306/jianw?serverTimezone=Asia/Shanghai&useUnicode=true
          jdbc.username: root
          jdbc.password: root
          druid.stat.enable: false
          druid.stat.slowSqlMillis: 1000


```
mytest_user.yml

```
dataSourceKey: defaultDS
destination: example
groupId: g1
outerAdapterKey: mysql1
concurrent: true
dbMapping:
  database: jianw
  table: t_baby_info
  targetTable: jianw.t_baby_info
  targetPk:
    id: id
  mapAll: true
  targetColumns:
    id:
    user_id:
    nick_name:
    gender:
    my_photo:
    learning_phase:
    create_time:
    update_time:
  etlCondition: "where update_time>={}"
  commitBatch: 3000 # 批量提交的大小


## Mirror schema synchronize config
#镜像库同步，要两库的表结构相同，只增量同步。
#dataSourceKey: defaultDS
#destination: example
#groupId: g1
#outerAdapterKey: mysql1
#concurrent: true
#dbMapping:
#  mirrorDb: true
#  database: jianw
```
