### ISSUE TITLE
docker-compose安装使用

### ISSUE THREAD

**Issue by Yourwon** [Yourwon/galibang#43]
一、下载

`https://github.com/docker/compose/releases`

`[root@iZ0 download]# wget https://github.com/docker/compose/releases/download/v2.33.1/docker-compose-linux-x86_64`
如果版本过高，会报 
```
[root@iZ0 download]# docker-compose up -d
compose build requires buildx 0.17 or later
```

二、移动到指定目录

`[root@ecs-88b9 download]# mv ./docker-compose-linux-x86_64 /usr/local/bin/docker-compose`

三、修改权限

`[root@ecs-88b9 download]# chmod +x /usr/local/bin/docker-compose`

四、查看版本

```
[root@ecs-88b9 download]# docker-compose --version

Docker Compose version v2.33.0
```

五、使用
docker-compose.yml可以放在任何目录，然后在该目录运行

```
docker-compose up -d  后台运行
docker-compose down --rmi all 停止并删除镜像
```

docker-compose.yml ，使用时，后边的注释删除

```
version: '3.8'  #指定Compose文件的版本



services:  #定义多个服务



  youj1:  #应用服务，可以是任何语言的后端服务

    image: youj-app:v1.01  # 使用镜像

    ports:

      - "9901:9101"  #将容器的9101端口映射到主机的9901端口

    restart: on-failure  #仅在容器非正常退出时重启



  youj2:  # 应用服务，可以是任何语言的后端服务

    build: /upload/images/youj2  # 重新构建

    ports:

      - "9902:9101"  # 将容器的9101端口映射到主机的9902端口

    restart: on-failure  # 仅在容器非正常退出时重启

    depends_on:

      - youj1  # 该服务将在'youju1'服务启动后才启动
```

从本地构建镜像，运行多个容器

```
services:
  stapi-1:
    build: /upload/images/short
    image: short-api:v1
    # 策略：只允许从本地构建，即使本地没有也不要去网上拉取同名镜像
    pull_policy: build
    ports:
      - "9090:9090"
    restart: on-failure
    
  stapi-2:
    image: short-api:v1
    # 策略：绝对不联网拉取。如果本地找不到 ，直接报错
    pull_policy: never    
    depends_on:
      - stapi-1
    ports:
      - "9091:9090"
    restart: on-failure
```
